<<<<<<< HEAD
name: CI Pipeline with Docker & Trivy
=======
name: CI/CD Pipeline with Trivy
>>>>>>> 25264b447ff59cd7736d082d626fa38c717ae9a0

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      BACKEND_IMAGE: varshap100/capstone-backend:latest
      FRONTEND_IMAGE: varshap100/capstone-frontend:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

<<<<<<< HEAD
      - name: Build backend image
        run: docker build -t $BACKEND_IMAGE ./backend

      - name: Build frontend image
=======
      - name: Build backend Docker image
        run: docker build -t $BACKEND_IMAGE ./backend

      - name: Build frontend Docker image
>>>>>>> 25264b447ff59cd7736d082d626fa38c717ae9a0
        run: docker build -t $FRONTEND_IMAGE ./frontend

      - name: Trivy scan backend image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.BACKEND_IMAGE }}
          severity: CRITICAL,HIGH
          exit-code: 0

      - name: Trivy scan frontend image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.FRONTEND_IMAGE }}
          severity: CRITICAL,HIGH
          exit-code: 0

      - name: Push backend image
        run: docker push $BACKEND_IMAGE

      - name: Push frontend image
        run: docker push $FRONTEND_IMAGE
<<<<<<< HEAD
=======

>>>>>>> 25264b447ff59cd7736d082d626fa38c717ae9a0
